import { readFileSync, existsSync } from 'fs'
import path from 'path'

/**
 * Force-static: the version is captured ONCE at build time and embedded
 * in the build artifact. This means it changes by construction on every
 * `next build` — no runtime filesystem access, no mtime guessing.
 *
 * The version is the .next/BUILD_ID (regenerated by Next.js on every build)
 * with a build-timestamp fallback.
 */
export const dynamic = 'force-static'

// Read BUILD_ID at build time (module load). If not available (dev mode),
// fall back to the current timestamp which always changes.
const BUILD_ID = (() => {
  try {
    const buildIdPath = path.join(process.cwd(), '.next', 'BUILD_ID')
    if (existsSync(buildIdPath)) {
      return readFileSync(buildIdPath, 'utf-8').trim()
    }
  } catch {}
  // Fallback: timestamp (changes every time in dev)
  return `dev-${Date.now()}`
})()

export function GET() {
  return new Response(
    JSON.stringify({ version: BUILD_ID, timestamp: Date.now() }),
    {
      headers: {
        'Content-Type': 'application/json',
        'Cache-Control': 'no-cache, no-store, must-revalidate',
      },
    }
  )
}
